sudo: required
dist: bionic
language: python
python: 3.8
services:
  - postgresql
addons:
  postgresql: '11'
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
install:
  - pip install pipenv
  - pipenv install --deploy --ignore-pipfile --dev
before_script:
  - psql -U postgres -f setup_db_and_user_for_travis.sql
  - pipenv run migrate
script:
  - pipenv run pytest --cov=.
